In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()        # Bunch는 딕셔너리를 랩핑한 것
type(iris)

sklearn.utils.Bunch

In [3]:
iris    # 기본적으로 data가 x, target이 y

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
import numpy as np
np.unique(y)                        # y는 종속변수의 모임, 카테고리가 3개인 것을 알 수 있다. 

array([0, 1, 2])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [7]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

In [21]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [9]:
log.coef_, log.intercept_

(array([[-0.41376612,  0.83766234, -2.34528437, -0.93645179],
        [ 0.44568418, -0.30720469, -0.16629699, -0.85401444],
        [-0.03191806, -0.53045764,  2.51158135,  1.79046624]]),
 array([  9.458684  ,   2.35967705, -11.81836105]))

y = -0.42161371x + 0.88072389x + -2.32676912x + -1.00668518x + 9.29253308

In [10]:
log.score(x_train,y_train)

0.9642857142857143

In [11]:
log.predict_proba(x_train[100:104])

array([[9.60292476e-01, 3.97072848e-02, 2.39715780e-07],
       [3.43714963e-06, 8.53669278e-03, 9.91459870e-01],
       [9.65541376e-01, 3.44585075e-02, 1.16437268e-07],
       [9.32752071e-01, 6.72476615e-02, 2.67476547e-07]])

In [12]:
log.predict(x_train[100:104])    # 결과값이 0,1,2기 때문게 가장 높은 수의 순서에 따라 나온다. 

array([0, 2, 0, 0])

In [13]:
2.07483482e-02 + 9.55524878e-01 + 2.37267741e-02

1.0000000003

In [14]:
from sklearn import metrics

In [15]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [16]:
y_pred  # 예측값

array([0, 0, 1, 1, 2, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 2, 0, 0, 0, 1, 2, 2,
       1, 2, 0, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2,
       2, 0, 2, 0, 1, 0, 2, 0, 2, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 2, 1, 2, 1, 1, 0, 2, 1, 2, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2,
       0, 2, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 1,
       1, 1])

In [17]:
y_train  # 원래값

array([0, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 1, 2, 0, 1, 2, 0, 0, 0, 1, 2, 2,
       1, 2, 0, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2,
       2, 0, 2, 0, 1, 0, 2, 0, 2, 0, 1, 0, 2, 0, 2, 2, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 2, 1, 2, 1, 1, 0, 2, 1, 2, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2,
       0, 2, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 1,
       1, 1])

In [18]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       0.93      0.98      0.95        42
           2       0.97      0.91      0.94        35

    accuracy                           0.96       112
   macro avg       0.97      0.96      0.96       112
weighted avg       0.96      0.96      0.96       112



In [19]:
metrics.confusion_matrix(y_train, y_pred)

array([[35,  0,  0],
       [ 0, 41,  1],
       [ 0,  3, 32]], dtype=int64)